---
repos:
  - repo: https://github.com/geek-kb/python_copilot_docs_hook
    rev: v0.1.20
    hooks:
      - id: python-copilot-docs
        additional_dependencies: ["openai>=1.0.0"]
        args: ["--openai-key", "${OPENAI_API_KEY}"]
        verbose: true

  - repo: https://github.com/geek-kb/python_docs_hook
    rev: v0.1.13
    hooks:
      - id: python-docs
        args: ["--doc-paths", "Scripts/simple_py_scripts"]
        verbose: false
        types: [python]
