---
repos:
  - repo: https://github.com/geek-kb/python_copilot_docs_hook
    rev: v0.1.3
    hooks:
      - id: python-copilot-docs
        verbose: true
        types: [python]
        environment:
          GITHUB_COPILOT_TOKEN: ${GITHUB_COPILOT_TOKEN}

  - repo: https://github.com/geek-kb/python_docs_hook
    rev: v0.1.13
    hooks:
      - id: python-docs
        args: ["--doc-paths", "Scripts/simple_py_scripts"]
        verbose: false
        types: [python]
