---

- name: check if consul is already installed
  stat: path=/usr/local/bin/consul
  register: consul_stat

- name: download consul
  get_url:
    url: https://releases.hashicorp.com/consul/{{ consul.version }}/consul_{{ consul.version }}_linux_amd64.zip
    dest: /tmp/consul.zip
    mode: '0600'
  when: not consul_stat.stat.exists

- name: unzip consul
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin
  when: not consul_stat.stat.exists

- name: create consul config directory
  file:
    path: "{{ consul.conf_dir }}"
    state: directory

- name: create consul data directory
  file:
    path: "{{ consul_config.data_dir }}"
    state: directory

- name: create consul scripts directory
  file:
    path: "{{ consul.conf_dir }}/scripts"
    state: directory

- name: generate consul encrypt key
  command: consul keygen
  register: keygen_output

- name: configure consul server conf
  template: src=server.json.j2 dest={{ consul.conf_dir }}/server.json

- name: configure consul consul conf
  template: src=consul.json.j2 dest={{ consul.conf_dir }}/consul.json

- name: configure consul-server service file
  template: src=consul-server.service.j2 dest=/etc/systemd/system/consul-server.service

- name: systemctl system-reload
  systemd:
    name: consul-server
    enabled: yes
    state: started
