---
# tasks file for filebeat

- name: remote install filebeat rpm
  yum: name="https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat.version }}-x86_64.rpm"

- name: configure filebeat
  template: src=filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml

- name: verify filebeat service is running
  systemd:
    name: filebeat
    enabled: yes
    state: restarted
