---
# tasks file for common
- name: verify strange versions of git are not installed
  yum:
    name: 'git[1-9]'
    state: absent
  tags: common.strange

- name: Install base packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - ansible
    - mlocate
    - iptables-services
    - vim
    - git
    - htop
    - curl
    - wget
    - bind-utils
    - net-tools
    - zip
    - unzip
    - screen
    - telnet
    state: latest
  when: ansible_distribution_major_version == "7"
