---

- name: verify Centos-Base repo is enabled
  command: sed -i '12,47{s/^enabled=0/enabled=1/g}' /etc/yum.repos.d/CentOS-Base.repo

- name: install centos-release repo
  yum:
    name: centos-release-scl-rh
    state: latest
  ignore_errors: yes

- name: install python3.6
  yum:
    name: rh-python36
    state: latest
  ignore_errors: yes

