---

- name: check if selinux is installed
  stat: path=/etc/selinux/config
  register: stat_selinux_result

- name: disable selinux
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=disabled'
  when: stat_selinux_result.stat.exists
