---

- name: check if vim is configured
  stat: path="{{ ansible_user_dir }}/.vimrc"
  register: vimrc_stat_result

- name: Create vim configuration file
  block:
    - name: create vim configuration file
      file:
        path: /root/.vimrc
        owner: root
        group: root
        mode: '0644'
        state: touch

    - name: Configure vim
      lineinfile:
        path: /root/.vimrc
        line: ':set ts=2'
        state: present
  when: not vimrc_stat_result.stat.exists
