apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: e-commerce
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
  storageClassName: gp2
  volumeMode: Filesystem

