#!/bin/bash
# This little script accepts AWS instance default hostname in the form of
# ip-1-2-3-4 and returns it in a valid IP format [1.2.3.4].
# If used on a MacOs, it also copies the valid IP to the local clipboard.
# Installation:
# chmod u+x and place in /usr/local/bin
# Usage:
# l2i ip-1-2-3-4
# Script by Itai Ganot, 2019

if [ -z $1 ]; then
	echo "Please supply a hostname in the convention of ip-1-1-1-1"
	exit 1
fi

var=$1
if [[ $(uname -s) == 'Darwin' ]]; then
	mac='True'
fi

if [[ $var =~ ^ip-.* ]]; then
	ip=$(echo $var | sed -e 's/^ip-//g' | tr "-" ".")
else
	ip=$(echo $var | tr "-" ".")
fi

if [[ $mac == 'True' ]]; then
	echo "Copied $ip to clipboard!"
	echo $ip | pbcopy
else
	echo $ip
fi
