---
# tasks file for cron
- name: configure cleanslave script in cron
  block:
  - name: copy script to its folder
    copy:
      src: "{{ role_path }}/files/cleanslave"
      dest: "{{ cron_scripts_path }}/cleanslave"
      owner: root
      group: root
      mode: '0700'
  - name: configure cron
    cron:
      name: "cleanslave"
      minute: "0"
      hour: "4"
      job: "{{ cron_scripts_path }}/cleanslave &>/dev/null"
