---
# tasks file for cron
- name: configure cron
  block:
  - name: verify server is a jenkins slave
    shell: echo "{{ ansible_hostname }}" | grep '^agent-c'
    register: jenkins_slave_result
    ignore_errors: yes
  - name: verify cleanslave script exists
    stat: path="{{ cron_scripts_path }}/cleanslave"
    register: cleanslave_result
  - import_tasks: cleanslave.yml
    when: jenkins_slave_result.rc == 0 and not cleanslave_result.stat.exists
  - name: create "{{ cron_scripts_path }}"
    file:
      name: "{{ cron_scripts_path }}"
      state: directory
      owner: "{{ cron_user }}"
      group: "{{ cron_group }}"
      mode: '0644'
  #- import_tasks: run_ansible_slave.yml
    #when: jenkins_slave_result == 0
  #- import_tasks: devops_git.yml
  #- import_tasks: run_ansible.yml
  - import_tasks: check_consul.yml
  - import_tasks: mlocate.yml
  - import_tasks: fix_hostname.yml
  tags: cron.configure
