---

- name: verify systemctl is used
  stat: path=/usr/bin/systemctl
  register: systemctl_result

- name: verify firewalld is stopped
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: systemctl_result.stat.exists
