---

- name: install node-exporter on centos 7
  block:
  - include: docker.yml
  - include: firewalld.yml
  - include: node-exporter_centos7.yml
  when: ansible_distribution_major_version == "7"
  tags: node_exporter.centos7.install

- name: install node-exporter on centos 6
  block:
  - include: node-exporter_centos6.yml
  when: ansible_distribution_major_version == "6"
  tags: node_exporter.centos6.install
