---
# tasks file for node-exporter
- name: pull node-exporter image
  docker_image:
    name: "{{ node_exporter_image }}"
    source: pull

- name: node_exporter container
  docker_container:
    name: node-exporter
    image: "{{ node_exporter_image }}:latest"
    state: started
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
    detach: yes
    command: --path.rootfs=/host

- name: register in consul
  uri:
    url: "{{ consul_api_address }}"
    method: PUT
    body: '{ "id": "{{ ansible_hostname }}", "name": "node_exporter", "address": "{{ ansible_default_ipv4.address }}", "port": 9100, "tags": [ "{{ ansible_hostname }}"] }'
    body_format: json
