apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-server
  name: db-server
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: db
status:
  loadBalancer: {}
