---
# tasks file for sshd
- name: verify ansible key exists
  block:
  - name: check if ansible_id_rsa exists
    stat: path="{{ ansible_user_dir }}/.ssh/ansible_id_rsa"
    register: ssh_key_result
    ignore_errors: yes
  - name: check md5sum of current key
    shell: md5sum "{{ ansible_user_dir }}/.ssh/ansible_id_rsa" | awk '{print $1}'
    register: ssh_key_md5_result
    ignore_errors: yes
    when: ssh_key_result.stat.exists

- debug:
    msg: "{{ ssh_key_result }}"

- debug:
    msg: "{{ ssh_key_md5_result }}"

- include_tasks: ssh_key.yml
  when: not ssh_key_result.stat.exists or ssh_key_md5_result.stdout != ssh.ansible_key_md5hash
