apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-get-put-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/itaig/data/mysql-get-put-pv/
  storageClassName: standard