apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-get-put-pvc
  namespace: dev
spec:
  selector:
    matchLabels:
      app: db-server
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: mysql-get-put-pv
  storageClassName: standard
