apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: db-server
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
      protocol: TCP
  selector:
    app: db-server
