apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: ubuntu:latest
      command: ["sleep", "9999"]
      env:
        - name: FNAME
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: FNAME
