groups:
  - name: default
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        identifier: '{{ $labels.instance }}'
        description: "{{ $labels.job }} has been down for more than 5 minutes."
    - alert: DiskSpace10%Free
      #expr: node_exporter:node_filesystem_free:fs_used_percents >= 10
      expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/",fstype!="rootfs"} * 100) / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"}) >= 90
      labels:
        severity: critical
      annotations:
        identifier: '{{ $labels.instance }}'
        description: "{{ $labels.instance }} has only {{ $value }}% free."
