apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: camelel/py-get-put:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_DATABASE
              value: getput
            - name: MYSQL_APP_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config-map 
                  key: MYSQL_APP_USER 
            - name: MYSQL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-user-pass
                  key: db_app_password.txt
            - name: MYSQL_HOST
              valueFrom: 
                configMapKeyRef:
                  name: db-config-map
                  key: MYSQL_HOST
            - name: MYSQL_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: MYSQL_TABLE_NAME 
