apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 80  # Exposed port for the service
      targetPort: 5000  # Port your Flask app listens on
  type: LoadBalancer  # Use "LoadBalancer" for cloud-based deployments
