apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-nodename
  name: php-nodename
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: php-nodename
  type: NodePort
