---
# defaults file for consul-client
consul:
  version: "1.6.2"
  user: "root"
  group: "root"
  var_dir: "/var/consul"
  datacenter: "company"
  conf_dir: "/etc/consul.d/client"
  encrypt_token: "TOKEN"
  server_address: "consul.company.com"
  dns_server_address1: "192.168.1.88"
  dns_server_address2: "192.168.1.68"
  bin_path: "/usr/local/bin"
  slaves_prefix: "agent"
dns:
  server_address1: "1.1.1.1"
  server_address2: "1.1.1.2"
  company_domain: "{{ consul.datacenter }}.com"
  company_consul_domain: "node.{{ consul.datacenter }}.consul"
