---
# defaults file for consul-client
consul_version: "1.6.2"
consul_user: "root"
consul_group: "root"
consul_var_dir: "/var/consul"
consul_datacenter: "company"
consul_config_dir: "/etc/consul.d/client"
consul_encrypt_token: "ENCRYPT_TOKEN"
consul_server_address: "consul.company.com"
dns_server_address1: "192.168.1.88"
dns_server_address2: "192.168.1.68"
bin_path: "/usr/local/bin"
slaves_prefix: "agent"
