---
# defaults file for consul-client
consul_version: "1.6.2"
consul_user: "consul"
consul_group: "consul"
consul_var_dir: "/var/consul"
consul_datacenter: "company"
consul_config_dir: "/etc/consul.d/client"
consul_encrypt_token: "" # just until Vault is implemented
consul_server_address: ""
dns_server_address: ""
bin_path: "/usr/local/bin"
