apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.name }}
spec:
  storageClassName: manual
  accessModes:
    - {{ .Values.pv.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pv.storage }}
