apiVersion: v1
kind: Service
metadata:
  name: {{ include "pingpong-helm.fullname" . }}
  labels:
{{ include "pingpong-helm.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "pingpong-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
