---
- name: check if server is a jenkins slave
  shell: hostname | grep "^{{ slaves_prefix }}"
  register: check_slave_result
  ignore_errors: yes

- name: download
  block:
    - name: download consul
      get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: /tmp/consul.zip
        mode: '0600'
    - name: unzip consul
      unarchive:
        src: /tmp/consul.zip
        dest: "{{ bin_path }}"
        remote_src: yes
  tags: consul.download

- name: configure
  block:
    - name: create consul client directory
      file:
        path: "{{ consul_config_dir }}"
        state: directory
    - name: create consul var directory
      file:
        path: "{{ consul_var_dir }}"
        state: directory
    - name: configure consul-client
      template: src=config.json.j2 dest="{{ consul_config_dir }}/config.json"
    - name: configure consul-client initd
      template:
        src: consul-client.chkconfig.j2
        dest: /etc/init.d/consul-client
        owner: root
        group: root
        mode: '0700'
    - name: configure dig to use search domain
      copy:
        src: "{{ role_path }}/files/.digrc"
        dest: "{{ ansible_user_dir }}/.digrc"
        mode: '0644'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
    - name: configure client as slave
      template: src=config_with_meta.json.j2 dest="{{ consul_config_dir }}/config.json"
      when: check_slave_result.rc == 0
  tags: consul.configure

- name: service restart
  service:
    name: consul-client
    enabled: yes
    state: restarted
