---

- name: download
  block:
    - name: download consul
      get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: /tmp/consul.zip
        mode: '0600'
    - name: unzip consul
      unarchive:
        src: /tmp/consul.zip
        dest: "{{ bin_path }}"
        remote_src: yes
  tags: consul.download

- name: configure
  block:
    - name: create consul client directory
      file:
        path: "{{ consul_config_dir }}"
        state: directory
    - name: create consul var directory
      file:
        path: "{{ consul_var_dir }}"
        state: directory
    - name: configure consul-client
      template: src=config.json.j2 dest="{{ consul_config_dir }}/config.json"
    - name: configure consul-client initd
      template:
        src: consul-client.chkconfig.j2
        dest: /etc/init.d/consul-client
        owner: root
        group: root
        mode: '0700'
  tags: consul.configure

- name: service restart
  service:
    name: consul-client
    enabled: yes
    state: restarted
