---

- name: check if server is a jenkins slave
  shell: hostname | grep "^{{ slaves_prefix }}"
  register: check_slave_result
  ignore_errors: yes

- name: download
  block:
    - name: download consul
      get_url:
        url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
        dest: /tmp/consul.zip
        mode: '0600'
    - name: unzip consul
      unarchive:
        src: /tmp/consul.zip
        dest: /usr/bin
        remote_src: yes
  tags: consul.download

- name: configure
  block:
    - name: create consul client directory
      file:
        path: /etc/consul.d/client
        state: directory
    - name: create consul var directory
      file:
        path: /var/consul
        state: directory
    - name: configure consul-client
      template: src=config.json.j2 dest={{ consul_config_dir }}/config.json
    - name: configure consul-client systemd
      template: src=consul-client.service.j2 dest=/etc/systemd/system/consul-client.service
    - name: configure client as slave
      template: src=config_with_meta.json.j2 dest="{{ consul_config_dir }}/config.json"
      when: check_slave_result.rc == 0
  tags: consul.configure

- name: systemctl daemon-reload
  systemd:
    name: consul-client
    enabled: yes
    daemon_reload: yes
    state: restarted
