---

- name: configure iptables to forward dns
  block:
  - name: redirect local dns udp
    iptables:
      table: nat
      chain: OUTPUT
      protocol: udp
      match: udp
      destination_port: '53'
      jump: REDIRECT
      to_ports: '8600'
      destination: localhost
  - name: redirect local dns tcp
    iptables:
      table: nat
      chain: OUTPUT
      protocol: tcp
      match: tcp
      destination_port: '53'
      jump: REDIRECT
      to_ports: '8600'
      destination: localhost
  tags: consul.iptables
